apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-graphql
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.64.1
    path: '/Users/matthewkeil/Documents/development/uc/server/src'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-graphql
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi