apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.64.1
    path: '/Users/matthewkeil/.kube/data/neo4j'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi